# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8294a26eda1226b4436f1f3c1f6a911aaf1f096c8fe7f65f56223831145de92a0a0340f39b3c6e2ae116fd43677957a794691e8a52c93a618bf69637c909848

test:
  secret_key_base: 9a08425fd71b3bed359cdcb1c862681e33f0d75d8862a63d78d6b7ed55f912448b161ddf57ff13fb4682579d7200c4fd5b4853397ea82d6e0fd22bee1519173e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
